// <auto-generated />
namespace TrialsAutumn2017.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class kossomy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kossomy));
        
        string IMigrationMetadata.Id
        {
            get { return "201709300118044_kossomy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
